language: csharp
dotnet: 3.1
mono: none
cache:
  directories:
    - $HOME/.nuget/packages
    - tests/explorer.api.tests/.vcr
install:
  - dotnet restore 
script:
  - dotnet build 
  - dotnet test --verbosity normal
