language: csharp
solution: explorer.sln
dotnet: 3.1
mono: none
cache:
  directories:
    - $HOME/.nuget/packages
    - tests/explorer.api.tests/.vcr
install:
  - dotnet restore explorer.sln
script:
  - dotnet build explorer.sln
  - dotnet test --verbosity normal explorer.sln
