language: csharp
solution: explorer.sln
dotnet: 3.1
mono: none
cache:
  directories:
    - $HOME/.nuget/packages
install:
  - dotnet restore explorer.sln
script:
  - dotnet build -warnAsError explorer.sln
  - dotnet test --verbosity normal explorer.sln
