version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src/aircloak/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
  - package_manager: "dotnet:nuget"
    directory: "/src/diffix"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
  - package_manager: "dotnet:nuget"
    directory: "/src/explorer"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
  - package_manager: "dotnet:nuget"
    directory: "/src/explorer.api"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
  - package_manager: "dotnet:nuget"
    directory: "/src/vcr-sharp"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"